-- AUTO COMMIT 비활성화하기
-- JOBS상세조회
	SELECT JOB_ID, JOB_TITLE , MIN_SALARY , MAX_SALARY 
	  FROM JOBS j
	  WHERE JOB_ID = 'IT_PROG';
	
-- JOBS전체조회
	SELECT JOB_ID, JOB_TITLE , MIN_SALARY , MAX_SALARY 
	  FROM JOBS j;

-- 입력(JOB_ID, JOB_TITLE 필수)

	INSERT INTO JOBS(JOB_ID, JOB_TITLE, MIN_SALARY,MAX_SALARY)
	 VALUES ('IT_DEV2','DEVELOPER','3000','5000');
	  
-- 수정
	UPDATE JOBS SET JOB_TITLE  = '개발자'
	 WHERE JOB_ID = 'IT_DEV2';
	
-- 삭제
	DELETE FROM JOBS
	 WHERE JOB_ID = 'IT_DEV2';
	 
	
	INSERT INTO BOARD
(SEQ, TITLE, CONTENT, REGDATE)
VALUES(0, '', '', '');

SELECT SEQ, TITLE, CONTENT, REGDATE
FROM BOARD;
